import fs from "node:fs";
import path from "node:path";
import { BIN_DIR, IS_WIN, launcherName, profileDir } from "./paths.js";

export const TOKEN_FILE = ".ccm-oauth-token";

// Launchers hardcode the absolute profile path for this machine and, if a
// .ccm-oauth-token file exists in the profile (macOS multi-account workaround),
// export it as CLAUDE_CODE_OAUTH_TOKEN before handing off to `claude`.

// Isolated profiles never self-update: the claude binary is shared, so updates
// happen once via the original installation (or "ccm update") and every profile
// picks the new version up on next launch. This avoids concurrent-update/lock
// errors when several profiles run at the same time.
function shShim(dir) {
  const shDir = dir.replaceAll("\\", "/");
  return `#!/bin/sh
# Generated by ccm - do not edit (regenerated by "ccm add").
export CLAUDE_CONFIG_DIR="${shDir}"
export DISABLE_AUTOUPDATER=1
if [ -f "$CLAUDE_CONFIG_DIR/${TOKEN_FILE}" ]; then
  CLAUDE_CODE_OAUTH_TOKEN="$(cat "$CLAUDE_CONFIG_DIR/${TOKEN_FILE}")"
  export CLAUDE_CODE_OAUTH_TOKEN
fi
exec claude "$@"
`;
}

function cmdShim(dir) {
  return `@echo off\r
rem Generated by ccm - do not edit (regenerated by "ccm add").\r
set "CLAUDE_CONFIG_DIR=${dir}"\r
set "DISABLE_AUTOUPDATER=1"\r
if exist "%CLAUDE_CONFIG_DIR%\\${TOKEN_FILE}" set /p CLAUDE_CODE_OAUTH_TOKEN=<"%CLAUDE_CONFIG_DIR%\\${TOKEN_FILE}"\r
claude %*\r
`;
}

function ps1Shim(dir) {
  return `# Generated by ccm - do not edit (regenerated by "ccm add").
$env:CLAUDE_CONFIG_DIR = "${dir}"
$env:DISABLE_AUTOUPDATER = "1"
$tokenFile = Join-Path $env:CLAUDE_CONFIG_DIR "${TOKEN_FILE}"
if (Test-Path $tokenFile) {
  $env:CLAUDE_CODE_OAUTH_TOKEN = (Get-Content $tokenFile -Raw).Trim()
}
claude @args
exit $LASTEXITCODE
`;
}

// Linked launchers deliberately leave the environment untouched so the command
// behaves exactly like running `claude` — same account, data and plugins.
const LINKED_SH = `#!/bin/sh
# Generated by ccm - linked to the DEFAULT Claude installation (no isolation).
exec claude "$@"
`;

const LINKED_CMD = `@echo off\r
rem Generated by ccm - linked to the DEFAULT Claude installation (no isolation).\r
claude %*\r
`;

const LINKED_PS1 = `# Generated by ccm - linked to the DEFAULT Claude installation (no isolation).
claude @args
exit $LASTEXITCODE
`;

export function launcherFiles(name) {
  const base = path.join(BIN_DIR, launcherName(name));
  return IS_WIN ? [base, `${base}.cmd`, `${base}.ps1`] : [base];
}

export function writeLauncher(name, { linked = false } = {}) {
  const dir = profileDir(name);
  fs.mkdirSync(BIN_DIR, { recursive: true });
  const base = path.join(BIN_DIR, launcherName(name));

  if (IS_WIN) {
    // npm-style triple shim so the command resolves from cmd, PowerShell and Git Bash.
    fs.writeFileSync(base, linked ? LINKED_SH : shShim(dir));
    fs.writeFileSync(`${base}.cmd`, linked ? LINKED_CMD : cmdShim(dir));
    fs.writeFileSync(`${base}.ps1`, linked ? LINKED_PS1 : ps1Shim(dir));
  } else {
    fs.writeFileSync(base, linked ? LINKED_SH : shShim(dir), { mode: 0o755 });
  }
  return base;
}

export function removeLauncher(name) {
  for (const file of launcherFiles(name)) {
    fs.rmSync(file, { force: true });
  }
}
